name: first_project_prophecy
description: ''
version: 1.0.0.1
author: yuan.yon@gmail.com
language: python
buildSystem: wheel
pipelines:
  pipelines/pipeline_1:
    name: pipeline_1
    description: ''
    author: yuan.yon@gmail.com
    mode: batch
    language: python
    createdAt: '2022-10-11 15:46:29'
    datasets:
      inputs:
      - 3633/datasets/jigsaw_mdt
      - 3633/datasets/pisystem_landing
      - 3633/datasets/diccionario
      outputs:
      - 3633/datasets/pisystem_join_to_delta
    dependencies: {}
datasets:
  datasets/jigsaw_mdt:
    name: jigsaw_mdt
    description: ''
    author: yuan.yon@gmail.com
    createdAt: '2022-10-11 16:00:21'
    physicalDatasets:
      dev-databricks-codelco:
        fabricId: 1084
        datasetType: File
        description: ''
        author: yuan.yon@gmail.com
        createdAt: '2022-10-11 16:00:21'
  datasets/pisystem_landing:
    name: pisystem_landing
    description: ''
    author: yuan.yon@gmail.com
    createdAt: '2022-10-11 18:26:23'
    physicalDatasets:
      dev-databricks-codelco:
        fabricId: 1084
        datasetType: File
        description: ''
        author: yuan.yon@gmail.com
        createdAt: '2022-10-11 18:26:23'
  datasets/diccionario:
    name: diccionario
    description: ''
    author: yuan.yon@gmail.com
    createdAt: '2022-10-11 18:57:16'
    physicalDatasets:
      dev-databricks-codelco:
        fabricId: 1084
        datasetType: Database
        description: ''
        author: yuan.yon@gmail.com
        createdAt: '2022-10-11 18:57:16'
  datasets/pisystem_join_to_delta:
    name: pisystem_join_to_delta
    description: ''
    author: yuan.yon@gmail.com
    createdAt: '2022-10-11 19:18:45'
    physicalDatasets:
      dev-databricks-codelco:
        fabricId: 1084
        datasetType: File
        description: ''
        author: yuan.yon@gmail.com
        createdAt: '2022-10-11 19:18:45'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
dependencies: []
